/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BiomeRatioEditor: typeof import('./src/components/BiomeRatioEditor.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MapGenerator: typeof import('./src/components/MapGenerator.vue')['default']
    MapPreview: typeof import('./src/components/MapPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
